name: Solidity CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      # --force to work around tableland/hardhat and tableland/local ^2.1.0-pre.0 incompatibility
      - run: npm i --force
      - run: npm run build
      - run: npm run test
