name: Solidity CI

on: [push]

jobs:
  test-parallel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: "npm"
      - run: npm i
      - run: npm run build
      - run: npm run test-parallel

  test-tableland:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: "npm"
      - run: npm i
      - run: npm run build
      - run: npm run test-tableland